name: PHP Simple CI #nom du workflow

# 1. Déclencheur (Trigger): Quand workflow doit-il s'executer ?
on:
  push:
    branches: ["main"] # S'execute quand on push sur la banche main

# 2. Jobs = la tache a executer (1 ou plusieurs)
jobs:
  build-and-test:
    #Définit l'environement sur lequel jobs va s'executer
    runs-on: ubuntu-latest
    # 3. les étapes = séquences d'actions
    steps:
      # 1. Recuperer le code du depot
      - name: Checkout Code
        uses: actions/checkout@v4 # Action GitHub officielle pour cloner le dépot
        # 2. Configurer PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" #Installe la version spécifique de PHP
          extensions: none
          coverage: none
          #3. Executer un test simple => verifié que le script s'execute sans erreur et affice une sortie attendue
      - name: Run simple PHP Script test
        run: |
          # 1. Capture de la sortie du script PHP
          OUTPUT=$(php index.php)
          EXPECTED_OUTPUT="Hello PHP"

          # 2. Comparaison
          if [ "$OUTPUT" != "$EXPECTED_OUTPUT" ]; then
            echo "--- Echec du Test ---"
            echo "Sortie attendue : $EXPECTED_OUTPUT"
            echo "Sortie obtenue : $OUTPUT"
            # Affichage d'une erreur formatée pour GitHub Actions
            echo "::error file=index.php::Le script n'a pas produit le contenu attendu."
            exit 1 # Rend le job rouge (échec)
          else
            echo "Test de contenu réussi : la sortie est conforme."
          fi
  deploy:
    needs: build-and-test #Execute le CD que si le CI a réussi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      #Utilise une action tierce
      - name: Deploy via SSH/SFTP
        uses: easingthemes/ssh-deploy@main # Utilisation d'une action fiable
        with:
          REMOTE_HOST: ${{secrets.SFTP_HOST}}
          REMOTE_USER: ${{secrets.SFTP_USERNAME}}
          SSH_PRIVATE_KEY: ${{secrets.SFTP_PASSWORD}}
          TARGET: ${{secrets.DEPLOY_PATH}}
          SOURCE: "./"
